version: '3.9'

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/api/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # env_file:
    #   - ./.env.dev.db
    environment:
      - POSTGRES_PASSWORD=biometric
      - POSTGRES_DB=biometric_dev
      - POSTGRES_USER=biometric

      
volumes:
  postgres_data: